### PR TITLE
Deep token getting

### PR DESCRIPTION
**Pull request by joelschou**
This is one way to handle enhancement #12. Give it a whirl!

### CODE REVIEW

**Comment by mirisuzanne** [comment]
This is nicely done, and a cool feature. I do have a few questions. 

- Can this be used inside a `#hash` alias, and can we add tests for that?
- What happens if I have `->` in a string, and neither side is a key, or the entire thing is a single key? How smoothly can we allow this to fail for backwards compatibility?

I'm editing this to merge into a 2.0 branch (`two`), since it's likely to be a breaking change. Can you resolve the conflict before we merge?

**Comment by joelschou** [comment]
Thanks!

- I actually ran into that very problem with hashes on Friday and have a fix locally I haven't yet pushed. Still needs a test or two. I also found a bug in it, wherein it got a little too eager to resolve up the hierarchy when inappropriate to do so. But since I have you on the horn, a question: I have it working with `#foo->bar->baz`, but should it also work with `#foo->#bar->#baz`? I haven't even tried it yet, so maybe it does!
- Right now it assumes the presence of a `->` in any form is a hierarchical divider. I supposed if it fails, we could try again with the string intact? I'm writing from a different computer right now, so I can't recall exactly how the new version works, but I'm fairly sure it's more granular in its approach and gives an opportunity to catch failures along the way instead of just barfing at the end. 😁 

As to your last comment about a breaking change: shouldn't be! It only runs on the string type in `_a_parse` and only then does anything if it finds a `->`. I tried really hard to just enhance and not ruin anything. But I guess I don't know for sure.

**Comment by mirisuzanne** [comment]
I would expect `#foo->bar->baz` inside a hashtag alias. The other reads as three individual aliases. I don't think it will work already, because we flip our key-lookup. Rather than determining an "end" to the hashtag (like a space, or period), we check to see if any available *keys* can be found at the 1-index. That way we don't have to worry about defining a alias-end pattern. For this, I would imagine doing similar down the chain after `->` strings that aren't already claimed? So that:

```scss
$map: (
  'this->that': 1,
  'foo': (
    'baz': 2,
  ),
  'bip': 'this->that', // this->that [not a hashtag]
  'bar': '#this->that', // 1 [-> used in valid key]
  'fop': '#foo->baz', // 2 [success!]
  'dop': '#foo->nope', // (baz: 2)->nope [follow until we fail, and leave what remains]
  'dip': '#this->baz', // '#this->baz' [don't follow a thread once it has failed]
);
```

Not sure if I covered all the edge cases there? That's my instinct. Thoughts?

Sounds like the (mostly) non-breaking version of this is support only in the initial request. That could still fail under the `this->that` condition above, but it's pretty unlikely. I think we should just go all in and do it as a major release, with the full feature supporting aliases :)

**Comment by joelschou** [comment]
So I'm a little leery on allowing `->` in keys. Take this:
```scss
$map: (
  'foo': (
    'bar': (
      'baz': 1
    ),
    'bar->baz': 2,
  'foo->bar': (
    'baz': 3
  ),
  'foo->bar->baz': 4
);
```
Next, consider `token-get( $map, 'foo->bar->baz' )`. It's reasonable to expect any one of `1`, `2`, `3`, or `4` as a return value. So then we have to start making some assumptions about specificity and precedence. 

If we're OK with that, I'd probably define the rules as "1) more `->` == higher score; 2) keys > values". So it'd go in this order:

1. `'foo->bar->baz' = 4`
2. `'foo->bar' : 'baz' = 3`
3. `'foo' : 'bar->baz' = 2`
4. `'foo' : 'bar' : 'baz' = 1`

_(For the record, the values going in perfect reverse order was a total coincidence.)_

**Comment by joelschou** [comment]
My latest push has the improved code started last week. I added tests to cover the scenarios you outlined, as well as two more to make sure we can go at least two levels deep. The one exception is tolerating `->` in keys/values as discussed above. The tests are there (commented out), but I didn't try solving it yet.

**Comment by joelschou** [comment]
OK, the commit history is an abject disaster, but the changes that came out at the end are right. This PR is now ready for you to evaluate and merge.

**Comment by mirisuzanne** [comment]
@joelschou This is real close, thanks! I started digging into the commented-out tests, and came up with a slightly different approach that *I think* handles all the edge cases, and passes all those tests. I'd love your feedback, if you have time to take a look at #22. 

Closing this PR for now, in favor of that one. I kept your commit history intact from here, so your contributions are still reflected in that branch.

**Pull request closed without merging**
