### PR TITLE
Joelschou-based deep get token

### PR DESCRIPTION
**Pull request by mirisuzanne**

### CODE REVIEW

**Comment by joelschou** [comment]
Your approach is much cleaner and less brute-force than mine. I'll pull it down and try it out in my current project to see if things still work as expected, but if the tests pass I'm sure everything will be fine (btw: I loooooove that you have tests)!

Aside, I added a variable in my fork for the nesting separator but haven't gotten around to PRing to you:
https://github.com/joelschou/accoutrement/commit/50d611f71d052094e12e09cfea24a2ff87b5239d

**Comment by mirisuzanne** [comment]
Yeah, I wondered about going that direction, but wasn't sure if there was a strong enough use-case? A single, consistent syntax-for-everyone will have fewer potential edge cases, and keep projects more inter-operable. Do you think the flexibility of a custom separator would be useful enough to outweigh that?

**Comment by mirisuzanne** [comment]
(tests have saved my ass so often, I can't live without them!)

**Comment by joelschou** [comment]
^^ I hadn't considered the inter-operable side of that discussion. I think the consistency of such _far_ outweighs any benefit gained from the custom separator. `->` FTW.

**Pull request merged**
