### PR TITLE
Integrate Accoutrement maps with CSS custom properties (variables)

### PR DESCRIPTION
**Pull request by mirisuzanne**
e.g…

```scss
// map definition
$colors: (
  'brand': hsl(120, 50%, 50%),
  'text': '#brand' ('shade': 50%),
  'border': '#text',
);

// create css color variables
:root {
  @include css-colors();
}

// access css color variables
.test {
  color: var-color('text');
  border-color: var-color('border', red); // provide a custom fallback
}
```

output:

```css
:root {
  --color-brand: #40bf40;
  --color-text: #206020;
  --color-border: var(--color-text, #206020); // simple references remain intact
}

.test {
  color: var(--color-text, #206020); // default fallback computes map value
  border-color: var(--color-border, red);
}
```

### CODE REVIEW

**Comment by joelschou** [comment]
This is a delightful feature. I started building something similar but never finished. It's like you're reading my mind for what we need at my job.

**Comment by mirisuzanne** [comment]
Does this look like the right approach to you?

For setting variables: 
- we provide the compiled value of each token
- for simple aliases, we use `var(--source-token, value)` to retain relationships

For calling variables:
- by default: we provide a fallback of the token's computed value
- you can override that fallback with any other value (or false/null to remove the fallback)

A few other ideas…

## "Private" Tokens:

```scss
$colors: (
  '_brand': hsl(120, 50%, 50%),
  'text': '#brand' ('shade': 50%),
  'border': '#text',
);

:root {
  --color-text: #206020;
  --color-border: var(--color-text, #206020);
}
```

## Changing an Alias:

```scss
:root {
  @include --color('border', 'text'); // var to set, token value to use
}

:root {
  --color-border: var(--color-text, #206020);
}
```

The `--color()` syntax was my best attempt at mimicking variable syntax, but it also makes the function look private…

**Comment by joelschou** [comment]
Yes, it does look right. In fact, it's quite a bit more straightforward than where I was headed, which is largely why I abandoned the approach (that, and we still need to support IE11 for our clients). I found myself in a pile of spaghetti pretty quickly and didn't care for it. Obviously I haven't tried your approach in my projects to know for sure, but I can see this being useful.

Your other ideas:

* I dig the private tokens a lot. I'm already using `$colors` as a big collection of color values that are used solely as inputs to obtain the real end-user colors. Being able to mark a significant portion of them as private would be great, as there's no reason for those private colors to end up in the browser as variables.
* I don't mind the `--color()` name because it does so closely mimic the final output. To me, underscores scream "private!" far more than do dashes, and while SASS doesn't distinguish, humans do and I think you're safe.

**Comment by mirisuzanne** [comment]
Downside of the `--color()` approach: I think the Sass 4.0 module system (still just a proposal) will consider variables/functions/mixins that start with a `_` or `-` to be private, and they will not be exported as part of the module. That approach may not work long-term. I'll look into that – in the meantime, I'm open to other ideas.

**Comment by mirisuzanne** [comment]
Are there other ways that we should account for private tokens in the parser? For example: 

- Font-names default to the earliest (`_a_origin`) source token a value, but could use the earliest non-private source…
- Throwing warnings or errors when you call a private tokens directly, seems too extreme…
- Other implications?

**Comment by joelschou** [comment]
* I'm afraid I don't have much input on font-names, unfortunately, as I hadn't used `accoutrement-type` before the big rebuild and just started implementing the type plugin a week or two ago.

* I completely agree about warnings or errors being too extreme. Functions and mixins marked private are completely accessible anywhere in a project, so there's really no need to do anything different for variables and tokens. As far as I'm concerned, "private" in SASS is a nice way of saying "this has an under-the-covers purpose and you probably don't need to worry about it so just move along." In this particular case, the benefit of private tokens is keeping them out of the rendered CSS...and that's about it. So maybe it's less a "private" thing and more like an "invisible" flag.

* The biggest implication I can think of right now is whether or not `_hello` and `hello` are the same thing. And then how references would work...which may be what you were asking about in the first bullet? Don't mind if I think this through out loud...

```scss
$foo: (
    '_hello': red,
    'hello': blue,
    'bar': '#hello'
);

get-token( $foo, 'bar' ); // ???
```

I've typed and deleted two different sets of thoughts here. Initially, I was thinking "they're obviously two separate tokens" and then I changed my mind to "the underscore is symbolic and can't affect the uniqueness of a token" and then I second-guessed my second-guessing and confused myself. The question becomes, "if the underscore is added to or removed from a token, does the consuming codebase need to be updated?" And I just don't know.

**Comment by joelschou** [comment]
All three of those reasons make total sense to me, especially the last one 😁

**Comment by mirisuzanne** [comment]
I'm told that Sass-items (functions/mixins/variables) starting with `-` will likely *not* be accessible to users in the new module syntax. No point adding that, if it will break soon. 

- For now, I've used `css-token()`, `css-color()`, and `css-size()` – but I'm not entirely happy with that.
- Maybe `token--()`, `color--()`, and `size--()`?

In other news: the color and scale plugins seemed like prime candidates for variables, so I started there. I'd like to get these right, and merge them in, before moving on. Animation and typography variables may also be useful, but will take a bit more thought.

**Pull request merged**
