### PR TITLE
Enhancement to tint and shade to use contrast-light and -dark

### PR DESCRIPTION
**Pull request by joelschou**
This might be going a little overboard, but it seems that if `contrast()` and `contrasted()` are going to automatically pull `contrast-light` and `contrast-dark`, we should let `tint()` and `shade()` do the same.

I considered adding a third argument to tint/shade for `$base`, just in case the developer wants to tint or shade with colors other than contrast-light and -dark. At that point, dropping down to `mix()` seems best?

_P.S. I don't know why those .html files have all the extra line breaks in them. Sorry._

### CODE REVIEW

**Comment by joelschou** [comment]
_Added issue #17_

**Comment by mirisuzanne** [comment]
This also needs a conflict resolved - but otherwise looks great, and ready to go. Changing the base branch to `two` until we're ready to release a 2.0 (probably soon with these new features - but may be nice to release the bugfix PR as a patch first).

**Comment by joelschou** [comment]
Welp. The conflict is resolved, but I seem to have sucked in the parsing bugfix (#19). Not sure if that's OK or not.

**Comment by mirisuzanne** [comment]
Hi, sorry I'm slow getting back to these. I had surgery, but I'm slowly getting back on the computer. Thanks for your patience, while I get my bearings back!

**Comment by mirisuzanne** [comment]
@joelschou That parsing fix was lovely. I just made a few code-formatting changes to match everything else – which should really be handled by a linter, or at least documented in a code style guide. That's my mistake, not yours. The logic remains the same as you wrote it.

This one also looks great. I'll clean up some final conflicts I caused, and get it merged in. Thanks!

**Comment by mirisuzanne** [comment]
Moved to #23 for final cleanup, with history intact…

**Pull request closed without merging**
