### PR TITLE
Modules

### PR DESCRIPTION
**Pull request by mirisuzanne**
## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

- run tests
- compile docs
- review docs
- beta release and live testing

# REMEMBER: Attach this PR to the Trello card

### CODE REVIEW

**Comment by mirisuzanne** [comment]
@jgerigmeyer not sure why the deploy preview isn't building here…

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer not sure why the deploy preview isn't building here…

Fixed, and link added to #43.

**Comment by jgerigmeyer** [comment]
@mirisuzanne @stacyk @dvdherron I think this is ready for review/merge/release whenever?

**Review by jgerigmeyer — APPROVED** [review]
:shipit:

**Comment by jgerigmeyer** [comment]
@mirisuzanne Do you want to give this a final 👍 before I merge and cut a beta release?

**Comment by dvdherron** [comment]
@mirisuzanne Missed [this](https://github.com/oddbird/time-designer/pull/1047#discussion_r764254781) change for the default value for `$content` in pseudo element mixins

Fixed [here](https://github.com/oddbird/accoutrement/pull/94/commits/18e6cea4137455a5fd6632a9574f28bfa0ecf53b)

**Review by dvdherron — APPROVED** [review]

**Review by mirisuzanne — COMMENTED** [review]
I opened the PR, so I can't approve. but 🤫 don't tell anyone, I say 👍🏼 (🙈).

**Pull request merged**
